services:
  jasperdb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=${JASPER_DB_USER}
      - MARIADB_PASSWORD=${JASPER_DB_PASSWORD}
      - MARIADB_DATABASE=${JASPER_DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${JASPER_DB_ROOT_PASSWORD}
    volumes:
      - 'jasperdb_data:/var/lib/mysql'

  jrs:
    image: gach24/jasper-report-server
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      - MARIADB_HOST=jasperdb
      - MARIADB_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=${JASPER_DB_USER}
      - JASPERREPORTS_DATABASE_PASSWORD=${JASPER_DB_PASSWORD}
      - JASPERREPORTS_DATABASE_NAME=${JASPER_DB_DATABASE}
      - JASPERREPORTS_USERNAME=${JASPER_REPORTS_USERNAME}
      - JASPERREPORTS_PASSWORD=${JASPER_REPORTS_PASSWORD}
    volumes:
      - 'jrs_data:/bitnami/jasperreports'
    depends_on:
      - jasperdb

  sakiladb:
    image: mariadb:latest
    environment:
      - MARIADB_USER=${SAKILA_DB_USER}
      - MARIADB_PASSWORD=${SAKILA_DB_PASSWORD}
      - MARIADB_DATABASE=${SAKILA_DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${SAKILA_DB_ROOT_PASSWORD}
    volumes:
      - 'sakila_data:/var/lib/mysql'
      - './sakila:/docker-entrypoint-initdb.d'
    ports:
      - '3306:3306'

volumes:
  jrs_data:
    driver: local
  jasperdb_data:
    driver: local
  sakila_data:
    driver: local
